- name: CREATE VM using Template
  hosts: all
  gather_facts: true
  vars:
    templateLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
    resgrp: 'Ansible-Workshop-DeployVMTemplate'
    location: 'westus'
    paramsLink: 'https://raw.githubusercontent.com/amalik99/azure-quickstart-templates/ansible-workshop-sampletemplates/101-vm-simple-linux/azuredeploy.parameters.json'
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resgrp }}'
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
        parameters_link: '{{ paramsLink }}'
