- name: CREATE RG Playbook
  hosts: all
  gather_facts: true
  
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: Ansible-Workshop-DeployVMTemplate
      location: westus
      tags:
          testing: testing
          delete: today
